apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv178studybot-mysql-pv-claim
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi